#ifndef Web_FWUpdate_h
#define Web_FWUpdate_h

#include "jquery_min_js_v3_2_1_gz.h"

const char FWUpdate[] PROGMEM = {
"<html>"
"<title>Firmware</title>"
"<script src='./jquery.min'></script>"
"<body>"
"<center>"
"Because of technical limitations, sometimes this update page does not completely load.<br/>"
"To circumvent this problem, please refresh your web browser before uploading new firmware.<br/><br/>"
"<form method='POST' action='./update' enctype='multipart/form-data' id='upload_form'>"
  "<input type='file' name='./update' accept='.bin' /><br/><br/>"
  "<input type='submit' value='Update'>"
"</form>"
"<div id='prg'>Progress: 0%</div>"
"</center>"
"<script>"
  "$('form').submit(function(e){"
    "e.preventDefault();"
    "var form = $('#upload_form')[0];"
    "var data = new FormData(form);"
    "$.ajax({"
             "url: './update',"
             "type: 'POST',"
             "data: data,"
             "contentType: false,"
             "processData:false,"
             "xhr: function() {"
               "var xhr = new window.XMLHttpRequest();"
               "xhr.upload.addEventListener('progress', "
                 "function(evt) {"
                   "if (evt.lengthComputable) {"
                     "var per = evt.loaded / evt.total;"
                     "$('#prg').html('Progress: ' + Math.round(per*100) + '%');"
                   "}"
                "}, false);"
              "return xhr;"
             "},"
             "success:function(d, s) {"
               "console.log('success!')"
             "},"
             "error: function (a, b, c) {"
             "}"
           "});"
  "});"
"</script>"
"</body>"
"</html>"};

#endif
